# Generated by Django 5.0.4 on 2024-04-29 15:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Histories',
            new_name='History',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
