# Generated by Django 5.0.4 on 2024-04-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_categories_category_rename_histories_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='decription',
        ),
    ]
